version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    networks:
      - keycloak_network
    command:
      - "start-dev"
networks:
  keycloak_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
